version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: always
    volumes:
      - ./:/app
    ports:
      - "${EXPOSE_PORT}:${VITE_PORT}"
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env
    command: yarn start